import { ArrowLeft, Clock3, Heart, Loader2, MapPin, Phone, Scissors, Star, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { addClientFavorite, getBookingDetails, getClientFavorites, getEstablishmentReviews, removeClientFavorite, type EstablishmentReview } from "../../api/client";
import type { EstablishmentBookingDetails } from "../../types/client";
import { formatCurrency, formatDuration } from "../../lib/format";
import { CollaboratorAvatar } from "../../components/collaborators/CollaboratorAvatar";
import { storage } from "../../utils/storage";

export default function EstablishmentPublicPage() {
  const id = Number(useParams().id);
  const [details, setDetails] = useState<EstablishmentBookingDetails>();
  const [reviews, setReviews] = useState<EstablishmentReview[]>([]);
  const [favorite, setFavorite] = useState(false);
  const [error, setError] = useState(false);
  const isClient = storage.getSession()?.role === "client";
  useEffect(() => { Promise.all([getBookingDetails(id), getEstablishmentReviews(id)]).then(([result, items]) => { setDetails(result); setReviews(items); }).catch(() => setError(true)); if (isClient) void getClientFavorites().then((items) => setFavorite(items.includes(id))); }, [id, isClient]);
  if (error) return <div className="mx-auto max-w-5xl px-4 py-16 text-sm text-red-700">Não foi possível carregar este estabelecimento.</div>;
  if (!details) return <div className="flex justify-center py-24"><Loader2 className="h-6 w-6 animate-spin text-[#0F5C56]" /></div>;
  const item = details.establishment;
  const now = new Date().toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" });
  const open = now >= item.open_hour.slice(0, 5) && now < item.close_hour.slice(0, 5);
  const mapUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(item.address)}`;
  return <div className="pb-16"><div className="relative h-56 bg-[#0F5C56]/10 sm:h-80">{item.cover_photo || item.photo ? <img src={item.cover_photo ?? item.photo ?? ""} alt={item.name} style={{ objectPosition: `50% ${item.cover_position ?? 50}%` }} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center"><Scissors className="h-12 w-12 text-[#0F5C56]/40" /></div>}<Link to="/" className="absolute left-4 top-4 flex items-center gap-2 rounded-full bg-white/95 px-4 py-2 text-sm shadow"><ArrowLeft className="h-4 w-4" />Voltar</Link></div>
    <main className="mx-auto max-w-5xl px-4 sm:px-6"><section className="relative -mt-8 rounded-2xl border border-[#E4E1D8] bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="th-display text-3xl font-semibold">{item.name}</h1><span className={`rounded-full px-2.5 py-1 text-xs ${open ? "bg-green-50 text-green-700" : "bg-[#12201E]/5 text-[#5C6B68]"}`}>{open ? "Aberto agora" : "Fechado agora"}</span></div><p className="mt-3 flex items-start gap-2 text-sm text-[#5C6B68]"><MapPin className="mt-0.5 h-4 w-4 shrink-0" />{item.address}</p><p className="mt-2 flex items-center gap-2 text-sm text-[#5C6B68]"><Clock3 className="h-4 w-4" />{item.open_hour.slice(0,5)} às {item.close_hour.slice(0,5)}</p>{item.description && <p className="mt-4 max-w-2xl text-sm leading-relaxed text-[#5C6B68]">{item.description}</p>}</div><div className="flex gap-2">{isClient && <button onClick={() => void (favorite ? removeClientFavorite(id) : addClientFavorite(id)).then(() => setFavorite(!favorite))} className="rounded-xl border border-[#E4E1D8] p-3" aria-label="Favoritar"><Heart className={`h-5 w-5 ${favorite ? "fill-red-500 text-red-500" : "text-[#5C6B68]"}`} /></button>}<Link to={`/estabelecimentos/${id}/agendar`} className="rounded-xl bg-[#0F5C56] px-5 py-3 text-center text-sm font-medium text-white">Agendar horário</Link></div></div><div className="mt-5 flex flex-wrap gap-3 border-t border-[#E4E1D8] pt-5"><a href={mapUrl} target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-xl border border-[#E4E1D8] px-4 py-2 text-sm"><MapPin className="h-4 w-4" />Abrir no mapa</a><a href={`tel:${item.phone}`} className="flex items-center gap-2 rounded-xl border border-[#E4E1D8] px-4 py-2 text-sm"><Phone className="h-4 w-4" />Entrar em contato</a></div></section>
      <div className="mt-7 grid gap-6 lg:grid-cols-2"><section className="rounded-2xl border border-[#E4E1D8] bg-white p-5"><h2 className="flex items-center gap-2 font-semibold"><Scissors className="h-4 w-4 text-[#0F5C56]" />Serviços</h2><div className="mt-4 divide-y divide-[#E4E1D8]">{details.services.map((service) => <div key={service.id} className="flex justify-between gap-4 py-4"><div><p className="font-medium">{service.name}</p><p className="text-xs text-[#5C6B68]">{formatDuration(service.duration_minutes)}</p></div><strong>{formatCurrency(service.price)}</strong></div>)}</div></section><section className="rounded-2xl border border-[#E4E1D8] bg-white p-5"><h2 className="flex items-center gap-2 font-semibold"><UserRound className="h-4 w-4 text-[#0F5C56]" />Profissionais</h2><div className="mt-4 grid gap-3">{details.collaborators.map((collaborator) => <div key={collaborator.id} className="flex items-center gap-3"><CollaboratorAvatar name={collaborator.name} photo={collaborator.photo} size="md" /><span>{collaborator.name}</span></div>)}</div></section></div>
      <section className="mt-6 rounded-2xl border border-[#E4E1D8] bg-white p-5"><h2 className="flex items-center gap-2 font-semibold"><Star className="h-4 w-4 text-[#F2A93B]" />Avaliações ({reviews.length})</h2>{reviews.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{reviews.map((review) => <article key={review.id} className="rounded-xl bg-[#F7F6F2] p-4"><p className="font-medium">{review.client_name}</p><p className="mt-1 text-xs text-[#F2A93B]">{"★".repeat(review.rating)}{"☆".repeat(5-review.rating)}</p>{review.comment && <p className="mt-2 text-sm text-[#5C6B68]">{review.comment}</p>}</article>)}</div> : <p className="mt-4 text-sm text-[#5C6B68]">Ainda não há avaliações.</p>}{item.cancellation_policy && <div className="mt-5 border-t border-[#E4E1D8] pt-5"><h3 className="text-sm font-medium">Política de cancelamento</h3><p className="mt-1 text-sm text-[#5C6B68]">{item.cancellation_policy}</p></div>}</section>
    </main></div>;
}
